version: '3'
services:
  db:
    image: postgres:13.6
    container_name: demo-postgres-13.6
      - postgres_data: /var/lib/postgresql/13/main
    command:
      "postgres -c 'max_connections=500'"
    environment:
      - POSTGRES_DB = ${POSTGRES_DB}
      - POSTGRES_USER = ${POSTGRES_USER}
    ports:
      - "5432:5432"
    demo-web:
      build: .
      command: "./bin/rails server"
      environment:
        - RAILS_ENV=${RAILS_ENV}
        - POSTGRES_HOST=${POSTGRES_HOST}
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_USER=${POSTGRES_USER}
        - RAILS_MASTER_KEY= ${RAILS_MASTER_KEY}
      volumes:
        - app-storage:/rails/storage
      depends_on:
        - db
      ports:
        - "3000:3000"

volumes:
  postgres_data: {}
  app_storage: {}
network:
  demo_default:
