default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  host: <%= ENV['POSTGRES_HOST'] %>
  timeout: 5000
  port: 5432

development:
  <<: *default
  database: docker_rails
  username: <%= ENV['POSTGRES_USER'] %>

test:
  <<: *default
  database: docker_rails_test
  username: <%= ENV['POSTGRES_USER'] %>

production:
  <<: *default
  database: docker_rails_pro
  username: <%= ENV['POSTGRES_DB'] %>
  username: <%= ENV['POSTGRES_USER'] %>
